### ISSUE TITLE
jupyter notebook can't show the charts but just output the address of the charts

### ISSUE THREAD

**Issue by huamingwang2014** [pyecharts/pyecharts-assets#1]
when I use the example from the guide doc, my jupyter just can't show the charts but output the address of the charts. my jupyter is offline because of some confidential requirements
, i have tried to download this piecharts-assets and then serving a localhost, change the CurrentConfig.ONLINE_HOST in my code, but it doesn't work... can you give me some suggestions?

**Comment by chenjiandongx** [comment]
@huamingwang2014 which jupyter environment do you use? notebook or lab?

**Comment by huamingwang2014** [comment]
my jupyter environment is notebook,

<img width="776" alt="image" src="https://user-images.githubusercontent.com/9329559/58748957-51077880-84b2-11e9-9b76-fa33da8df8b7.png">

<img width="699" alt="image" src="https://user-images.githubusercontent.com/9329559/58748985-962baa80-84b2-11e9-9ab1-a37d425671a6.png">

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/58749011-d0954780-84b2-11e9-801c-0c425208b573.png)

Notebook don't need to specify Notebook_TPYE and use load_javascript() function

**Comment by chenjiandongx** [comment]
The only thing you need is set `CurrentConfig.ONLINE_HOST= 'your_local_asset_host'`
