### ISSUE TITLE
localhost_server mode can not render pics with Chinese words

### ISSUE THREAD

**Issue by lihantao3** [pyecharts/pyecharts-assets#16]
在离线环境下，调用下载到本地的pyecharts-assets渲染图片，自定义的中文不能正常渲染

**Comment by sunhailin-Leo** [comment]
@lihantao3 
* 什么意思？有具体解释？

**Comment by lihantao3** [comment]
> @lihantao3
> 
> * 什么意思？有具体解释？

内网环境使用，下载了pyecharts-assets(https://github.com/pyecharts/pyecharts-assets)，指定online_host为本地server，渲染出来的图表，中文内容会乱码，呈现空白框
![image](https://user-images.githubusercontent.com/32725201/152670780-3336fbdd-4df5-4a8d-ac66-883cf8d84242.png)
